steps:
  # Grab cached M2 repo
  - name: gcr.io/cloud-builders/gsutil
    id: Get M2 Cache
    args: ['cp', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz', 'm2.tar.gz']
      #
  # See https://github.com/GoogleCloudPlatform/cloud-builders-community to get the tar command
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Expand M2 Cache
    args: ['xpzf', 'm2.tar.gz']

  - name: 'maven:3-jdk-11'
    id: Maven Package
    env:
      - TZ=Europe/London
    args: ['-Dmaven.repo.local=/workspace/.m2/repository', 'package']
    entrypoint: mvn

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-service:$BRANCH_NAME-$SHORT_SHA', '-f', 'cloudbuild.docker', '.' ]

  # Update M2 repo cache
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Compress M2 Cache
    args: ['cpzf', 'm2.tar.gz', '.m2']

  - name: gcr.io/cloud-builders/gsutil
    id: Save M2 Cache
    args: ['cp', 'm2.tar.gz', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz']

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: bash
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      apt-get update
      apt-get install -y gnupg
      curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
      curl -Os https://uploader.codecov.io/latest/alpine/codecov
      curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
      curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM.sig
      gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
      sha256sum -c codecov.SHA256SUM
      ls
      chmod +x codecov
      ./codecov

images: [ 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-service:$BRANCH_NAME-$SHORT_SHA' ]




