logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework: OFF
  profile: CLOUD

cloud:
  gcp:
    pubsub:
      subscriber:
        flow-control:
          max-outstanding-element-count: 100
