#
# This docker compose file assumes that you have set the DOCKER_GCP_CREDENTIALS environment
# variable to point at a json file which contains valid GCP credentials. 
# The credentials file may be either a downloaded credentials file for your personal GCP
# environment (see the Readme) or the credentials than are refreshed by running:
#    $ gcloud auth application-default login
# 
# It is also assumed that the GOOGLE_CLOUD_PROJECT environment variable is set. This should contain
# the name of your GCP project, eg, sdc-rh-fred
#

version: '3.8'
services:

  mock-envoy:
    container_name: mock-envoy
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/mock-envoy:latest
    ports:
      - "8181:8181"

  pubsub-emulator:
    container_name: pubsub-emulator
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/pubsubemu:latest
    ports:
      - "9808:8085"

  firestore-emulator:
    container_name: rh-firestore-emulator
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/gcloud-firestore-emulator:latest
    ports:
      - "8542:8540"

  rh-service:
    container_name: rh-service
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/rh-service:latest
    ports:
    - "8071:8071"
    volumes:
    - type: bind
      source: $DOCKER_GCP_CREDENTIALS
      target: /gcp/config/google-credentials.json
      read_only: true
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/google-credentials.json
    - ${VAR_FIRESTORE_EMULATOR_HOST:-VAR_DUMMY_REPLACEMENT}=rh-firestore-emulator:8540
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    - spring.profiles.active=local
    - spring.cloud.gcp.pubsub.emulator-host=host.docker.internal:9808
    - rate-limiter.rest-client-config.host=host.docker.internal
    - MANAGEMENT_METRICS_EXPORT_STACKDRIVER_ENABLED=false
